name: Publish to Itch.io

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v5.2.1
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.5-stable/Godot_v4.5-stable_export_templates.tpz
          relative_project_path: ./untitled-paint-game/
          archive_output: true
          # Use the GitHub Actions workflow cache to cache the Godot export templates and Godot executable. 
          # Helps speed up builds by not having to download them every time.
          cache: true
        env:
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}

      - name: Publish to Itch
        uses: manleydev/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{secrets.ITCH_IO_TOKEN}}
          CHANNEL: html5
          ITCH_GAME: untitled-paint-game
          ITCH_USER: jx24
          PACKAGE: ${{ steps.export.outputs.archive_directory }}/upgame-web.zip
          VERSION: ${{ github.sha }}
